/**
 *
 * @author rohen
 */
public class login extends javax.swing.JFrame {

    /**
     * Creates new form login
     */
    public login() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated
    // Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        loginFormLeftJPanel = new javax.swing.JPanel();
        companyNameJLabel = new javax.swing.JLabel();
        developersJLabel = new javax.swing.JLabel();
        technocratsAddressJLabel = new javax.swing.JLabel();
        technocratsNumJLabel = new javax.swing.JLabel();
        technocratsEmailJLabel = new javax.swing.JLabel();
        loginFormRightJPanel = new javax.swing.JPanel();
        closeLoginFormJLabel = new javax.swing.JLabel();
        LoginJLabel = new javax.swing.JLabel();
        UserNameJLabel = new javax.swing.JLabel();
        UserNameJTextField = new javax.swing.JTextField();
        PasswordJLabel = new javax.swing.JLabel();
        PasswordJTextField = new javax.swing.JTextField();
        loginJButton = new javax.swing.JButton();
        cancelJButton = new javax.swing.JButton();
        createNewAccJLabel = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        loginFormLeftJPanel.setBackground(new java.awt.Color(255, 255, 255));

        companyNameJLabel.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
        companyNameJLabel.setForeground(new java.awt.Color(255, 195, 0));
        companyNameJLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        companyNameJLabel.setText("CLOTHED UNDER GRACE");

        developersJLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        developersJLabel.setText("© 2022 Order Management System. All rights reserved | Designed by Technocrats");

        technocratsAddressJLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        technocratsAddressJLabel.setText("UWI Mona, Kingston 7.");

        technocratsNumJLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        technocratsNumJLabel.setText("+1 876 1234567 | +1 876 9876543");

        technocratsEmailJLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        technocratsEmailJLabel.setText("technocrats@gmail.com ");

        javax.swing.GroupLayout loginFormLeftJPanelLayout = new javax.swing.GroupLayout(loginFormLeftJPanel);
        loginFormLeftJPanel.setLayout(loginFormLeftJPanelLayout);
        loginFormLeftJPanelLayout.setHorizontalGroup(
                loginFormLeftJPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(companyNameJLabel, javax.swing.GroupLayout.DEFAULT_SIZE,
                                javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(developersJLabel, javax.swing.GroupLayout.DEFAULT_SIZE, 570, Short.MAX_VALUE)
                        .addComponent(technocratsAddressJLabel, javax.swing.GroupLayout.Alignment.TRAILING,
                                javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE,
                                Short.MAX_VALUE)
                        .addComponent(technocratsNumJLabel, javax.swing.GroupLayout.Alignment.TRAILING,
                                javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE,
                                Short.MAX_VALUE)
                        .addComponent(technocratsEmailJLabel, javax.swing.GroupLayout.Alignment.TRAILING,
                                javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE,
                                Short.MAX_VALUE));
        loginFormLeftJPanelLayout.setVerticalGroup(
                loginFormLeftJPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(loginFormLeftJPanelLayout.createSequentialGroup()
                                .addGap(136, 136, 136)
                                .addComponent(companyNameJLabel)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 175,
                                        Short.MAX_VALUE)
                                .addComponent(developersJLabel)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(technocratsAddressJLabel)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(technocratsNumJLabel)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(technocratsEmailJLabel)
                                .addGap(19, 19, 19)));

        getContentPane().add(loginFormLeftJPanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 570, 460));

        loginFormRightJPanel.setBackground(new java.awt.Color(255, 195, 0));

        closeLoginFormJLabel.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        closeLoginFormJLabel.setForeground(new java.awt.Color(255, 255, 255));
        closeLoginFormJLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        closeLoginFormJLabel.setText("X");
        closeLoginFormJLabel.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        closeLoginFormJLabel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                closeLoginFormJLabelMouseClicked(evt);
            }
        });

        LoginJLabel.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        LoginJLabel.setForeground(new java.awt.Color(255, 255, 255));
        LoginJLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        LoginJLabel.setText("LOGIN");

        UserNameJLabel.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        UserNameJLabel.setForeground(new java.awt.Color(255, 255, 255));
        UserNameJLabel.setText("Username");

        UserNameJTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                UserNameJTextFieldActionPerformed(evt);
            }
        });

        PasswordJLabel.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        PasswordJLabel.setForeground(new java.awt.Color(255, 255, 255));
        PasswordJLabel.setText("Password");

        PasswordJTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                PasswordJTextFieldActionPerformed(evt);
            }
        });

        loginJButton.setForeground(new java.awt.Color(255, 195, 0));
        loginJButton.setText("LOGIN");

        cancelJButton.setForeground(new java.awt.Color(255, 195, 0));
        cancelJButton.setText("CANCEL");

        createNewAccJLabel.setForeground(new java.awt.Color(255, 255, 255));
        createNewAccJLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        createNewAccJLabel.setText("Click here to create a new account");

        javax.swing.GroupLayout loginFormRightJPanelLayout = new javax.swing.GroupLayout(loginFormRightJPanel);
        loginFormRightJPanel.setLayout(loginFormRightJPanelLayout);
        loginFormRightJPanelLayout.setHorizontalGroup(
                loginFormRightJPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(loginFormRightJPanelLayout.createSequentialGroup()
                                .addGroup(loginFormRightJPanelLayout
                                        .createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addGroup(loginFormRightJPanelLayout.createSequentialGroup()
                                                .addContainerGap()
                                                .addGroup(loginFormRightJPanelLayout
                                                        .createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                        .addComponent(LoginJLabel,
                                                                javax.swing.GroupLayout.Alignment.TRAILING,
                                                                javax.swing.GroupLayout.DEFAULT_SIZE,
                                                                javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING,
                                                                loginFormRightJPanelLayout.createSequentialGroup()
                                                                        .addGap(0, 0, Short.MAX_VALUE)
                                                                        .addComponent(closeLoginFormJLabel,
                                                                                javax.swing.GroupLayout.PREFERRED_SIZE,
                                                                                37,
                                                                                javax.swing.GroupLayout.PREFERRED_SIZE))))
                                        .addGroup(loginFormRightJPanelLayout.createSequentialGroup()
                                                .addGroup(loginFormRightJPanelLayout
                                                        .createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                        .addGroup(loginFormRightJPanelLayout.createSequentialGroup()
                                                                .addGap(44, 44, 44)
                                                                .addGroup(loginFormRightJPanelLayout
                                                                        .createParallelGroup(
                                                                                javax.swing.GroupLayout.Alignment.LEADING,
                                                                                false)
                                                                        .addComponent(UserNameJLabel,
                                                                                javax.swing.GroupLayout.PREFERRED_SIZE,
                                                                                74,
                                                                                javax.swing.GroupLayout.PREFERRED_SIZE)
                                                                        .addComponent(PasswordJLabel,
                                                                                javax.swing.GroupLayout.PREFERRED_SIZE,
                                                                                74,
                                                                                javax.swing.GroupLayout.PREFERRED_SIZE)
                                                                        .addComponent(PasswordJTextField,
                                                                                javax.swing.GroupLayout.DEFAULT_SIZE,
                                                                                292, Short.MAX_VALUE)
                                                                        .addComponent(UserNameJTextField)))
                                                        .addGroup(loginFormRightJPanelLayout.createSequentialGroup()
                                                                .addGap(82, 82, 82)
                                                                .addComponent(loginJButton,
                                                                        javax.swing.GroupLayout.PREFERRED_SIZE, 93,
                                                                        javax.swing.GroupLayout.PREFERRED_SIZE)
                                                                .addGap(34, 34, 34)
                                                                .addComponent(cancelJButton,
                                                                        javax.swing.GroupLayout.PREFERRED_SIZE, 93,
                                                                        javax.swing.GroupLayout.PREFERRED_SIZE)))
                                                .addGap(0, 48, Short.MAX_VALUE)))
                                .addContainerGap())
                        .addComponent(createNewAccJLabel, javax.swing.GroupLayout.Alignment.TRAILING,
                                javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE,
                                Short.MAX_VALUE));
        loginFormRightJPanelLayout.setVerticalGroup(
                loginFormRightJPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(loginFormRightJPanelLayout.createSequentialGroup()
                                .addComponent(closeLoginFormJLabel)
                                .addGap(40, 40, 40)
                                .addComponent(LoginJLabel)
                                .addGap(34, 34, 34)
                                .addComponent(UserNameJLabel)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(UserNameJTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 36,
                                        javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(31, 31, 31)
                                .addComponent(PasswordJLabel)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(PasswordJTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 36,
                                        javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(49, 49, 49)
                                .addGroup(loginFormRightJPanelLayout
                                        .createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(loginJButton, javax.swing.GroupLayout.PREFERRED_SIZE, 32,
                                                javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(cancelJButton, javax.swing.GroupLayout.PREFERRED_SIZE, 32,
                                                javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 55,
                                        Short.MAX_VALUE)
                                .addComponent(createNewAccJLabel)
                                .addGap(34, 34, 34)));

        getContentPane().add(loginFormRightJPanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(570, 0, 390, 460));

        setSize(new java.awt.Dimension(958, 456));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void closeLoginFormJLabelMouseClicked(java.awt.event.MouseEvent evt) {// GEN-FIRST:event_closeLoginFormJLabelMouseClicked
        // TODO add your handling code here:
        System.exit(0);
    }// GEN-LAST:event_closeLoginFormJLabelMouseClicked

    private void UserNameJTextFieldActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_UserNameJTextFieldActionPerformed
        // TODO add your handling code here:
    }// GEN-LAST:event_UserNameJTextFieldActionPerformed

    private void PasswordJTextFieldActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_PasswordJTextFieldActionPerformed
        // TODO add your handling code here:
    }// GEN-LAST:event_PasswordJTextFieldActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {

        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        // </editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new login().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel LoginJLabel;
    private javax.swing.JLabel PasswordJLabel;
    private javax.swing.JTextField PasswordJTextField;
    private javax.swing.JLabel UserNameJLabel;
    private javax.swing.JTextField UserNameJTextField;
    private javax.swing.JButton cancelJButton;
    private javax.swing.JLabel closeLoginFormJLabel;
    private javax.swing.JLabel companyNameJLabel;
    private javax.swing.JLabel createNewAccJLabel;
    private javax.swing.JLabel developersJLabel;
    private javax.swing.JPanel loginFormLeftJPanel;
    private javax.swing.JPanel loginFormRightJPanel;
    private javax.swing.JButton loginJButton;
    private javax.swing.JLabel technocratsAddressJLabel;
    private javax.swing.JLabel technocratsEmailJLabel;
    private javax.swing.JLabel technocratsNumJLabel;
    // End of variables declaration//GEN-END:variables
}
