package project3.orderman.invoice.login;

import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.text.SimpleDateFormat;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;

/**
 *
 * @author rohen
 */
public class registerForm extends javax.swing.JFrame {

    /**
     * Creates new form registerForm
     */
    public registerForm() {
        initComponents();
        this.setLocationRelativeTo(null); // Center form in screen
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        headerJPanel = new javax.swing.JPanel();
        regisCloseJLabel = new javax.swing.JLabel();
        regisMinimizeJLabel = new javax.swing.JLabel();
        RegisterJLabel = new javax.swing.JLabel();
        regisInfoJPanel = new javax.swing.JPanel();
        jLabelFirstName = new javax.swing.JLabel();
        jTextFieldFirstName = new javax.swing.JTextField();
        jLabelLastName = new javax.swing.JLabel();
        jTextFieldLastName = new javax.swing.JTextField();
        jLabelUsername = new javax.swing.JLabel();
        jTextFieldUsername = new javax.swing.JTextField();
        jLabelPassword = new javax.swing.JLabel();
        jLabelPassword1 = new javax.swing.JLabel();
        jPasswordField = new javax.swing.JPasswordField();
        jPasswordFieldReType = new javax.swing.JPasswordField();
        jButtonRegister = new javax.swing.JButton();
        jButtonCancel = new javax.swing.JButton();
        jLabelBday = new javax.swing.JLabel();
        jLabelAddress = new javax.swing.JLabel();
        jLabelGoToLogin = new javax.swing.JLabel();
        jDateChooser = new com.toedter.calendar.JDateChooser();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTextAreaAddress = new javax.swing.JTextArea();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        headerJPanel.setBackground(new java.awt.Color(255, 195, 0));

        regisCloseJLabel.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        regisCloseJLabel.setForeground(new java.awt.Color(255, 255, 255));
        regisCloseJLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        regisCloseJLabel.setText("X");
        regisCloseJLabel.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        regisCloseJLabel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                regisCloseJLabelMouseClicked(evt);
            }
        });

        regisMinimizeJLabel.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        regisMinimizeJLabel.setForeground(new java.awt.Color(255, 255, 255));
        regisMinimizeJLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        regisMinimizeJLabel.setText("-");
        regisMinimizeJLabel.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        regisMinimizeJLabel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                regisMinimizeJLabelMouseClicked(evt);
            }
        });

        RegisterJLabel.setFont(new java.awt.Font("Segoe UI", 1, 21)); // NOI18N
        RegisterJLabel.setForeground(new java.awt.Color(255, 255, 255));
        RegisterJLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        RegisterJLabel.setText("Register");

        javax.swing.GroupLayout headerJPanelLayout = new javax.swing.GroupLayout(headerJPanel);
        headerJPanel.setLayout(headerJPanelLayout);
        headerJPanelLayout.setHorizontalGroup(
            headerJPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, headerJPanelLayout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addComponent(RegisterJLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 94, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 308, Short.MAX_VALUE)
                .addComponent(regisMinimizeJLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(regisCloseJLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        headerJPanelLayout.setVerticalGroup(
            headerJPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, headerJPanelLayout.createSequentialGroup()
                .addGroup(headerJPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(headerJPanelLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(regisMinimizeJLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                        .addGap(10, 10, 10))
                    .addComponent(regisCloseJLabel, javax.swing.GroupLayout.DEFAULT_SIZE, 24, Short.MAX_VALUE))
                .addGap(46, 46, 46))
            .addGroup(headerJPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(RegisterJLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        getContentPane().add(headerJPanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 500, 70));

        regisInfoJPanel.setBackground(new java.awt.Color(0, 53, 102));

        jLabelFirstName.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabelFirstName.setForeground(new java.awt.Color(255, 255, 255));
        jLabelFirstName.setText("First Name:");

        jLabelLastName.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabelLastName.setForeground(new java.awt.Color(255, 255, 255));
        jLabelLastName.setText("Last Name:");

        jLabelUsername.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabelUsername.setForeground(new java.awt.Color(255, 255, 255));
        jLabelUsername.setText("Username:");

        jLabelPassword.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabelPassword.setForeground(new java.awt.Color(255, 255, 255));
        jLabelPassword.setText("Password:");

        jLabelPassword1.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabelPassword1.setForeground(new java.awt.Color(255, 255, 255));
        jLabelPassword1.setText("Re-Type Pw:");

        jButtonRegister.setBackground(new java.awt.Color(81, 152, 235));
        jButtonRegister.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jButtonRegister.setForeground(new java.awt.Color(255, 255, 255));
        jButtonRegister.setText("Register");
        jButtonRegister.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButtonRegister.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButtonRegisterMouseClicked(evt);
            }
        });
        jButtonRegister.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonRegisterActionPerformed(evt);
            }
        });

        jButtonCancel.setBackground(new java.awt.Color(243, 63, 63));
        jButtonCancel.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jButtonCancel.setForeground(new java.awt.Color(255, 255, 255));
        jButtonCancel.setText("Cancel");
        jButtonCancel.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));

        jLabelBday.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabelBday.setForeground(new java.awt.Color(255, 255, 255));
        jLabelBday.setText("Birth-date:");

        jLabelAddress.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabelAddress.setForeground(new java.awt.Color(255, 255, 255));
        jLabelAddress.setText("Address:");

        jLabelGoToLogin.setForeground(new java.awt.Color(255, 255, 255));
        jLabelGoToLogin.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelGoToLogin.setText("Click here to Login");
        jLabelGoToLogin.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabelGoToLogin.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabelGoToLoginMouseClicked(evt);
            }
        });

        jTextAreaAddress.setColumns(20);
        jTextAreaAddress.setRows(5);
        jScrollPane1.setViewportView(jTextAreaAddress);

        javax.swing.GroupLayout regisInfoJPanelLayout = new javax.swing.GroupLayout(regisInfoJPanel);
        regisInfoJPanel.setLayout(regisInfoJPanelLayout);
        regisInfoJPanelLayout.setHorizontalGroup(
            regisInfoJPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(regisInfoJPanelLayout.createSequentialGroup()
                .addGroup(regisInfoJPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(regisInfoJPanelLayout.createSequentialGroup()
                        .addGap(42, 42, 42)
                        .addGroup(regisInfoJPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(regisInfoJPanelLayout.createSequentialGroup()
                                .addComponent(jLabelFirstName, javax.swing.GroupLayout.PREFERRED_SIZE, 74, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(jTextFieldFirstName, javax.swing.GroupLayout.PREFERRED_SIZE, 286, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(regisInfoJPanelLayout.createSequentialGroup()
                                .addComponent(jLabelLastName, javax.swing.GroupLayout.PREFERRED_SIZE, 74, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(jTextFieldLastName, javax.swing.GroupLayout.PREFERRED_SIZE, 286, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(regisInfoJPanelLayout.createSequentialGroup()
                                .addComponent(jLabelUsername, javax.swing.GroupLayout.PREFERRED_SIZE, 74, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(jTextFieldUsername, javax.swing.GroupLayout.PREFERRED_SIZE, 286, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(regisInfoJPanelLayout.createSequentialGroup()
                                .addComponent(jLabelPassword, javax.swing.GroupLayout.PREFERRED_SIZE, 74, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(jPasswordField)))
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(regisInfoJPanelLayout.createSequentialGroup()
                        .addGap(44, 44, 44)
                        .addGroup(regisInfoJPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabelPassword1)
                            .addComponent(jLabelBday)
                            .addComponent(jLabelAddress))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(regisInfoJPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(regisInfoJPanelLayout.createSequentialGroup()
                                .addComponent(jButtonRegister, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(43, 43, 43)
                                .addComponent(jButtonCancel, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jPasswordFieldReType)
                            .addComponent(jDateChooser, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jScrollPane1))))
                .addGap(80, 80, 80))
            .addComponent(jLabelGoToLogin, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        regisInfoJPanelLayout.setVerticalGroup(
            regisInfoJPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(regisInfoJPanelLayout.createSequentialGroup()
                .addGap(28, 28, 28)
                .addGroup(regisInfoJPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(regisInfoJPanelLayout.createSequentialGroup()
                        .addGroup(regisInfoJPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabelFirstName)
                            .addComponent(jTextFieldFirstName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(28, 28, 28)
                        .addGroup(regisInfoJPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jTextFieldLastName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabelLastName))
                        .addGap(28, 28, 28)
                        .addGroup(regisInfoJPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jTextFieldUsername, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabelUsername))
                        .addGap(28, 28, 28)
                        .addGroup(regisInfoJPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabelPassword)
                            .addComponent(jPasswordField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(28, 28, 28)
                        .addGroup(regisInfoJPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jPasswordFieldReType, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabelPassword1))
                        .addGap(28, 28, 28)
                        .addComponent(jLabelBday))
                    .addComponent(jDateChooser, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(28, 28, 28)
                .addGroup(regisInfoJPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabelAddress)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 112, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 26, Short.MAX_VALUE)
                .addGroup(regisInfoJPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jButtonRegister, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButtonCancel, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jLabelGoToLogin)
                .addGap(20, 20, 20))
        );

        getContentPane().add(regisInfoJPanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 70, 500, 550));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void regisMinimizeJLabelMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_regisMinimizeJLabelMouseClicked
        this.setState(registerForm.ICONIFIED); //minimize form
    }//GEN-LAST:event_regisMinimizeJLabelMouseClicked

    private void regisCloseJLabelMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_regisCloseJLabelMouseClicked
        System.exit(0); //close form
    }//GEN-LAST:event_regisCloseJLabelMouseClicked

    private void jButtonRegisterMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButtonRegisterMouseClicked
        
    }//GEN-LAST:event_jButtonRegisterMouseClicked

    private void jLabelGoToLoginMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabelGoToLoginMouseClicked
        login lgf= new login(); //When clicked, login form pops up
        lgf.setVisible(true); 
        lgf.pack();
        lgf.setLocationRelativeTo(null); //centers form
        lgf.setDefaultCloseOperation(login.EXIT_ON_CLOSE);
        this.dispose(); //closes registration form when login form pops up
    }//GEN-LAST:event_jLabelGoToLoginMouseClicked

    private void jButtonRegisterActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonRegisterActionPerformed
        // TODO add your handling code here:
        String fname= jTextFieldFirstName.getText();
        String lname= jTextFieldLastName.getText();
        String uname= jTextFieldUsername.getText();
        String pass= String.valueOf(jPasswordField.getPassword());
        String retype_pass= String.valueOf(jPasswordFieldReType.getPassword());
        
        SimpleDateFormat dateformat= new SimpleDateFormat("yyyy-MM-dd");
        String bdate= dateformat.format(jDateChooser.getDate());        
        String address= jTextAreaAddress.getText();
        
        if (fname.isEmpty() || lname.isEmpty() || uname.isEmpty()
                || pass.isEmpty() || retype_pass.isEmpty() || jDateChooser.getDate()== null || address.isEmpty()){
            JOptionPane.showMessageDialog(null, "Please complete all fields.");
        }
        else if(!pass.equals(retype_pass)){
            JOptionPane.showMessageDialog(null, "Passwords don't match. Re-type the password again");
        }
        else{
            //Start login process
            userRegister(fname, lname, uname, pass, bdate, address);
        }
    }//GEN-LAST:event_jButtonRegisterActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(registerForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(registerForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(registerForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(registerForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new registerForm().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel RegisterJLabel;
    private javax.swing.JPanel headerJPanel;
    private javax.swing.JButton jButtonCancel;
    private javax.swing.JButton jButtonRegister;
    private com.toedter.calendar.JDateChooser jDateChooser;
    private javax.swing.JLabel jLabelAddress;
    private javax.swing.JLabel jLabelBday;
    private javax.swing.JLabel jLabelFirstName;
    private javax.swing.JLabel jLabelGoToLogin;
    private javax.swing.JLabel jLabelLastName;
    private javax.swing.JLabel jLabelPassword;
    private javax.swing.JLabel jLabelPassword1;
    private javax.swing.JLabel jLabelUsername;
    private javax.swing.JPasswordField jPasswordField;
    private javax.swing.JPasswordField jPasswordFieldReType;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextArea jTextAreaAddress;
    private javax.swing.JTextField jTextFieldFirstName;
    private javax.swing.JTextField jTextFieldLastName;
    private javax.swing.JTextField jTextFieldUsername;
    private javax.swing.JLabel regisCloseJLabel;
    private javax.swing.JPanel regisInfoJPanel;
    private javax.swing.JLabel regisMinimizeJLabel;
    // End of variables declaration//GEN-END:variables

    private void userRegister(String fname, String lname, String uname, String pass, String bdate, String address) {
        Connection dbconn= myConnection.connectDB();
        if(dbconn != null){
        try {
            PreparedStatement st= (PreparedStatement)
                    dbconn.prepareStatement("INSERT INTO users (firstname,lastname,username,password,bday,address) VALUES(?,?,?,?,?,?)");
            
            st.setString(1, fname);
            st.setString(2, lname);
            st.setString(3, uname);
            st.setString(4, pass);
            st.setString(5, bdate);
            st.setString(6, address);
            
            int res= st.executeUpdate();
            JOptionPane.showMessageDialog(this, "User data added.", "Success", JOptionPane.INFORMATION_MESSAGE);

            jTextFieldFirstName.setText("");
            jTextFieldLastName.setText("");
            jTextFieldUsername.setText("");
            jPasswordField.setText("");
            
            jTextAreaAddress.setText("");
            
            
        } catch (SQLException ex) {
            Logger.getLogger(login.class.getName()).log(Level.SEVERE, null, ex);
        }
        }else{
            System.out.println("The connection is not available");
        }
    }
}
